#!/bin/bash

usage() {
	echo "Incorrect usage."
	echo "Usage: genmaster <PATH_TO_UNIT>"
	exit 0;
}

if [[ -z $1 ]]
then
	usage
fi

currentDirectory="`pwd`"

# Change directory to unit in question
cd "$1"

# Initialize directory structure in /tmp for initial i/o operations
mkdir -p /tmp/notes/
if [ -e /tmp/notes/master.md ]; then
	rm /tmp/notes/master.md
fi
echo "" > /tmp/notes/master.md

# Populating /tmp/notes/master.md
shopt -s dotglob
shopt -s nullglob
files=(*.md)
for file in "${files[@]}"; do
	if [ ! "$file" == "master.md" ]; then
		echo -e "# $(echo "$file" | sed 's/\.md//g')\n" >> /tmp/notes/master.md
		cat "$file" >> /tmp/notes/master.md
		echo -e "\n\n---\n\n" >> /tmp/notes/master.md
	fi
done
sed -i '1d' /tmp/notes/master.md
sed -i '$ d' /tmp/notes/master.md
sed -i '$ d' /tmp/notes/master.md
sed -i '$ d' /tmp/notes/master.md
sed -i '$ d' /tmp/notes/master.md
sed -i '$ d' /tmp/notes/master.md


if [[ ! ( ( -e "./master.md" ) && ( -z "`diff /tmp/notes/master.md ./master.md`" ) ) ]]; then
	echo "Generating master document..."
	cp /tmp/notes/master.md ./master.md
	pandoc -s -f markdown -o master.pdf --latex-engine=pdflatex master.md
fi


cd "$currentDirectory"
