#!/bin/bash

#Store current directory so we can cd to it at the end of the script
currentDirectory="`pwd`"

usage() {
	echo "Incorrect usage.  This script does not take parameters."
	echo "Usage: ugenmaster"
}


if [ ! -z "$1" ]; then
	usage
	exit
fi

NOTES_DIRECTORY="/home/jake/notes"

cd $NOTES_DIRECTORY

baseDirectories=(*/)

for container in "${baseDirectories[@]}"; do
	if [ ! "$container" == "scripts/" ]; then
		cd "$container"
		containerDirectories=(*/)
		for subcontainer in "${containerDirectories[@]}"; do
			cd "$subcontainer"
			subcontainerDirectories=(*/)
			for unit in "${subcontainerDirectories[@]}"; do
				cd "$unit"
				
				#Code to run on each unit
				printf "Processing %s/%s%s%s\n" "$NOTES_DIRECTORY" "$container" "$subcontainer" "$unit"
				genmaster "`pwd`"

				cd ..
			done
			cd ..
		done
		cd ..
	fi
done

cd "$currentDirectory"
