#!/bin/sh

USAGE () {
	echo "Incorrect usage."
	echo "usage: ugenmaster [--force-all]"
}

# If more than one parameter was passed, exit
if [ "$#" -gt "1" ]; then
	USAGE
	exit -1
fi

FORCE_ALL=0 # Default behavior is to not force rebuilds of the pdfs; this feature probably shouldn't be used unless the way you tell pandoc
            # to generate pdf's changes somehow(like a change of template or something)

# Now that we know there are either 0 or 1 parameters, we have to check them
for parameter in "$@"
do
	if [ "$parameter" == "--force-all" ]; then
		FORCE_ALL=1
	else
		USAGE
		exit -1
	fi
done


REPO_DIR="/home/jake/notes"

NOTES_DIR="${REPO_DIR}/notes"

# If you want to omit certain directories from being detected as units, add them here
UNIT_BLACKLIST=("${NOTES_DIR}")

# Set IFS to newline, so that we can iterate over directories that have tabs or spaces in their names
IFS="
"

for dir in `find "$NOTES_DIR" -type d -not -path '*/\.*' | sort`; do # Iterate over each non-hidden(e.g. .git/) subdirectory
	
	# If $dir is equivalent to one of the elements of $UNIT_BLACKLIST, continue to the next iteration of the loop(skip the current value)
	for blacklisted_directory in "${UNIT_BLACKLIST[@]}"; do
		if [ "$dir" == "$blacklisted_directory" ]; then
			continue 2;
		fi
	done
	
	# Now that we know $dir isn't blacklisted, we call genmaster on it if it contains markdown files
	if ls "$dir"/*.md &> /dev/null; then
		# Lastly, check for force build
		if [ "$FORCE_ALL" -eq "0" ]; then
			genmaster "$dir"
		else
			genmaster "$dir" --force
		fi
	fi
done
